FROM python:3.10-slim

# Встановлюємо системні залежності (FFmpeg)
RUN apt-get update && apt-get install -y ffmpeg

# Налаштовуємо робочу папку
WORKDIR /app

# Копіюємо файли
COPY . /app

# Встановлюємо бібліотеки Python
RUN pip install --no-cache-dir -r requirements.txt

# Запускаємо бота
CMD ["python", "bot.py"]